// components/dashboard/import-panel.tsx
"use client";

import { RunButton } from "@/components/run-button";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { FlaskConical } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

const SOURCE_LOGOS = [
  { src: "/logos/stripe.svg", alt: "Stripe" },
  { src: "/logos/gumroad.svg", alt: "Gumroad" },
  { src: "/logos/dodo.webp", alt: "Dodo Payments" },
  { src: "/logos/chase.svg", alt: "Bank" },
] as const;

type State = "idle" | "uploading" | "sampling" | "error";

export function ImportPanel({
  redirectAfterUpload = false,
  canReconcile = false,
  showSources = true,
}: {
  redirectAfterUpload?: boolean;
  canReconcile?: boolean;
  showSources?: boolean;
}) {
  const router = useRouter();
  const [state, setState] = useState<State>("idle");
  const [error, setError] = useState<string | null>(null);
  const [names, setNames] = useState<string[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const busy = state === "uploading" || state === "sampling";

  async function submit(kind: "uploading" | "sampling", request: () => Promise<Response>) {
    setState(kind);
    setError(null);
    const response = await request();
    if (!response.ok) {
      const payload = (await response.json().catch(() => null)) as { error?: string } | null;
      setError(payload?.error ?? "Import failed. Retry.");
      setState("error");
      return;
    }
    setState("idle");
    if (redirectAfterUpload) router.push("/dashboard");
    else router.refresh();
  }

  function upload(fileList: FileList | null) {
    if (!fileList || fileList.length === 0) return;
    const form = new FormData();
    const picked: string[] = [];
    for (const file of Array.from(fileList)) {
      form.append("files", file);
      picked.push(file.name);
    }
    setNames(picked);
    void submit("uploading", () => fetch("/api/import", { method: "POST", body: form }));
  }

  function loadSample() {
    setNames([]);
    void submit("sampling", () => fetch("/api/sample", { method: "POST" }));
  }

  return (
    <div className="flex w-full flex-col gap-5">
      <Card className="rounded-none border-black/15 py-0">
        <CardContent className="p-5">
          <label
            htmlFor="import-files"
            onDragEnter={(event) => {
              event.preventDefault();
              setIsDragging(true);
            }}
            onDragOver={(event) => event.preventDefault()}
            onDragLeave={(event) => {
              event.preventDefault();
              setIsDragging(false);
            }}
            onDrop={(event) => {
              event.preventDefault();
              setIsDragging(false);
              upload(event.dataTransfer.files);
            }}
            className={`flex min-h-48 w-full cursor-pointer flex-col items-center justify-center gap-3 border border-dashed px-5 py-6 text-center transition-colors focus-within:ring-2 focus-within:ring-ring ${
              isDragging ? "border-primary bg-secondary" : "border-black/25 hover:border-primary hover:bg-secondary/50"
            }`}
          >
            <img src="/logos/excel.svg" alt="" className="h-12 w-12" />
            <p className="text-sm text-muted-foreground">
              {state === "uploading" ? "Importing files…" : "Drop files here"}
            </p>
            <span
              className={`inline-flex min-h-10 items-center bg-primary px-4 text-sm font-medium text-primary-foreground ${
                busy ? "invisible" : ""
              }`}
            >
              Choose files
            </span>
            {names.length > 0 ? (
              <span className="font-mono text-[11px] text-muted-foreground">{names.join(" · ")}</span>
            ) : null}
            <input
              id="import-files"
              type="file"
              accept=".csv,.json,text/csv,application/json"
              multiple
              disabled={busy}
              className="sr-only"
              onChange={(event) => {
                upload(event.target.files);
                event.target.value = "";
              }}
            />
          </label>
          {error ? <p className="mt-3 text-center text-sm text-destructive">{error}</p> : null}
        </CardContent>
        <CardFooter className="flex items-center justify-between gap-3 border-t border-black/10 bg-transparent px-5 py-4">
          <Button type="button" variant="ghost" size="sm" disabled={busy} onClick={loadSample}>
            <FlaskConical aria-hidden="true" />
            {state === "sampling" ? "Loading sample…" : "Use sample data"}
          </Button>
          {redirectAfterUpload ? null : <RunButton disabled={!canReconcile || busy} />}
        </CardFooter>
      </Card>
      {showSources ? (
        <div className="flex items-center justify-center gap-x-5">
          <span className="whitespace-nowrap text-sm text-muted-foreground">Works with</span>
          <ul className="flex items-center gap-x-5" aria-label="Supported sources">
            {SOURCE_LOGOS.map((logo) => (
              <li key={logo.src}>
                <img src={logo.src} alt={logo.alt} className="h-5 w-auto" />
              </li>
            ))}
          </ul>
        </div>
      ) : null}
    </div>
  );
}

// src/lib/components/ImportPanel.svelte
<script lang="ts">
 import { invalidateAll, goto } from '$app/navigation';
 import { Upload, RefreshCw, CheckCircle2 } from 'lucide-svelte';
 let { compact=false, canReconcile=false, redirect=false }:{compact?:boolean;canReconcile?:boolean;redirect?:boolean}=$props();
 let state=$state<'idle'|'uploading'|'running'|'error'>('idle'); let error=$state(''); let imported=$state<number|null>(null); let dragging=$state(false);
 async function submit(body:FormData){state='uploading';error='';try{const r=await fetch('/api/import',{method:'POST',body});const data=await r.json();if(!r.ok)throw new Error(data.error||'Import failed');imported=data.events?.length??data.eventCount??null;state='idle';await invalidateAll();if(redirect)goto('/dashboard')}catch(e){error=e instanceof Error?e.message:'Import failed';state='error'}}
 function upload(files:FileList|null){if(!files?.length)return;const form=new FormData();for(const f of files)form.append('files',f);void submit(form)}
 async function run(){state='running';error='';try{const r=await fetch('/api/reconcile',{method:'POST'});if(!r.ok)throw new Error('Reconciliation failed');state='idle';imported=null;await invalidateAll()}catch(e){error=e instanceof Error?e.message:'Reconciliation failed';state='error'}}
</script>
<div class:compact class="import card">
 <div class="processors" aria-hidden="true"><img src="/logos/stripe.svg" alt=""/><img class="dodo" src="/logos/dodo.webp" alt=""/><img class="icon" src="/logos/gumroad.svg" alt=""/><img src="/logos/chase.svg" alt=""/></div>
 <label class:dragging ondragenter={(e)=>{e.preventDefault();dragging=true}} ondragover={(e)=>e.preventDefault()} ondragleave={()=>dragging=false} ondrop={(e)=>{e.preventDefault();dragging=false;upload(e.dataTransfer?.files??null)}}>
  <span class="upload-icon"><Upload size={19}/></span>
  <span class="copy"><b>{state==='uploading'?'Importing files…':'Drop files or browse'}</b><small>Upload <code>data/judges-test.json</code>, or Stripe / Dodo Payments / Gumroad / bank CSV and JSON</small></span>
  <span class="choose">Choose files</span>
  <input aria-label="Upload source files" type="file" accept=".csv,.json" multiple onchange={(e)=>{upload(e.currentTarget.files);e.currentTarget.value=''}}/>
 </label>
 {#if !redirect}<div class="import-actions"><button class="btn" onclick={run} disabled={!canReconcile||state==='running'}><span class:spin={state==='running'}><RefreshCw size={15}/></span>{state==='running'?'Reconciling…':'Run reconciliation'}</button></div>{/if}
 {#if imported!==null}<p class="notice good"><CheckCircle2 size={15}/>{imported} events imported and ready.</p>{/if}
 {#if error}<p class="notice bad">{error}</p>{/if}
</div>
<style>
 .import{overflow:hidden}
 .processors{display:flex;align-items:center;gap:16px;padding:10px 16px;border-bottom:1px solid var(--line);background:#fff}
 .processors img{height:16px;width:auto;object-fit:contain}
 .processors img.dodo{height:22px;border-radius:50%}
 .processors img.icon{height:18px}
 .import label{display:flex;align-items:center;gap:14px;padding:16px;min-height:78px;transition:.15s}
 .import label:hover,.import label.dragging{background:#f5f8f1}
 .upload-icon{width:42px;height:42px;display:grid;place-items:center;background:#edf3e9;border-radius:9px;color:var(--green)}
 .copy{display:grid;gap:4px;flex:1}
 .copy b{font-size:13px}
 .copy small{font-size:11px;color:var(--muted);line-height:1.45}
 .copy code{font:10px 'IBM Plex Mono';background:#efefe8;padding:1px 5px;border-radius:4px}
 .choose{border:1px solid var(--line);border-radius:8px;padding:9px 13px;font-size:11px;font-weight:650;background:white}
 .import input{position:absolute;opacity:0;width:1px;height:1px}
 .import-actions{padding:10px 14px;border-top:1px solid var(--line);background:#fafbf8;display:flex;justify-content:flex-end}
 .import-actions .btn{min-height:37px;font-size:11px}
 .notice{margin:0;padding:9px 16px;border-top:1px solid var(--line);display:flex;gap:7px;align-items:center;font-size:11px}
 .spin{display:inline-flex;animation:spin 1s linear infinite}
 @keyframes spin{to{transform:rotate(360deg)}}
 @media(max-width:560px){.choose{display:none}.processors{gap:12px}}
</style>
